name: Deploy VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 207.180.211.88
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/silvercat_tools
            git pull origin main
